apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  layout:
    type: three-panel
    panels:
      - type: endpoint-list
        width: 25%
      - type: endpoint-details
        width: 50%
      - type: additional-information
        width: 25%
