name: Lebena Documentation CD/CI
on: 
  push:
    branches:
      - "main"
jobs:
 
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: dist
        remote: /var/www/lebena
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
